### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by dstern** [sradiouy/UTRme#1]
I have installed UTRme via conda, but it is far from obvious how to launch the program from the installed packages.
Within the utrme folder within the anaconda envs folder I find a collection of folders, and none of them contains something that looks like a launchable application

I am also wondering why you have not provided a command-line version of this useful tool. This would be much easier to launch on a cluster, which is where I do most of my heavy-lifting analysis.

I look forward to trying your software.

Many thanks, David

**Comment by sradiouy** [comment]
Hi David,

We are currently updating UTRme to add a command line version. Within a few
weeks it will be available.

Best regards,

Santiago

**Comment by dstern** [comment]
That’s super!
Any chance you can provide some advice to allow me to run the app version for now?

On Apr 23, 2019, at 6:39 PM, Santiago Radio <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi David,

We are currently updating UTRme to add a command line version. Within a few
weeks it will be available.

Best regards,

Santiago

**Comment by sradiouy** [comment]
Hi David! The new version is available! With new GUI and command line
option. You must create a configuration file in order to avoid the GUI.
Please see the README.

**Comment by dstern** [comment]
That’s great! Thanks.
I have installed on our cluster and got it running part way.

It errored out on faidx

> Running faidx!

Traceback (most recent call last):
  File "/groups/stern/home/sternd/bin/UTRme/utrme.py", line 1626, in <module>
    main()
  File "/groups/stern/home/sternd/bin/UTRme/utrme.py", line 1538, in main
    closest = bedtools(Genome,Annotation,directory,feature,identificator,logger)
  File "/groups/stern/home/sternd/bin/UTRme/utrme.py", line 432, in bedtools
    chrom_sizes = chrom_size(genome,dirout,logger)
  File "/groups/stern/home/sternd/bin/UTRme/utrme.py", line 394, in chrom_size
    stdout = runcml(commandLine,"faidx","faidx error",logger,True)
  File "/groups/stern/home/sternd/bin/UTRme/utrme.py", line 195, in runcml
    process = subprocess.Popen(cml.split(),stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=False)
  File "/misc/local/python27/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/misc/local/python27/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


In the *.log file, the faidx comand looks incomplete.

2019-04-26 20:19:55,248 - UTRme - INFO - > Running faidx!

2019-04-26 20:19:55,248 - UTRme - INFO - faidx /groups/stern/home/sternd/UTR/genome.fasta -i chromsizes

I am not familiar with the command faidx on its own, but in samtools I am unfamiliar with an -i command.


On Apr 26, 2019, at 1:41 PM, Santiago Radio <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi David! The new version is available! With new GUI and command line
option. You must create a configuration file in order to avoid the GUI.
Please see the README.

**Comment by sradiouy** [comment]
Can you run this: faidx /groups/stern/home/sternd/UTR/genome.fasta -i
chromsizes in the command line, and tell me the output?


Remember to do it in the UTRme env

**Comment by sradiouy** [comment]
Also the configuration file it would be useful. Thanks.

**Comment by dstern** [comment]
My bad!
I was not running within the conda environment.
Seems to be working now.

On Apr 27, 2019, at 12:31 AM, Santiago Radio <notifications@github.com<mailto:notifications@github.com>> wrote:

Also the configuration file it would be useful. Thanks.

**Comment by dstern** [comment]
I spoke too soon.
Crashed because did not, apparently, copy over the gff file correctly to the temp workspace.
Here is the bedtools command
***********
2019-04-27 12:20:57,194 - UTRme - INFO - > Running bedtools sorting!

2019-04-27 12:20:57,194 - UTRme - INFO - bedtools sort -i /groups/stern/home/sternd/bin/UTRme/UTRme_2019-04-27_08-11-30/temp/temp.gff
2019-04-27 12:20:57,971 - UTRme - INFO - bedtools sorting had a execution time of: 00:00:00.78
************
And the temp.gff file is missing.
This is strange because it was copied properly when I was running this from within the folder that contained the original gff file.

Here is the config file that indicates the location of the gff file.
*************
temporary_value:YES
excel_value:NO
N_value:NO
score_value:NO
utr3_value:YES
utr5_value:YES
mmap_value:YES
core_value:16
adapter_value:AGATCGGAAGAGC
id_value:ID=
orf_value:200
len3_value:3000
len5_value:1000
error_value:0.05
overlap_value:5
feature_value:CDS
basename_value:Hcor
sl_value:
organism_value:H.cornu
experiment_value:Paired-end
annotation_value:/groups/stern/home/sternd/hormaphis/UTR/augustus.min.gtf
genome_value:/groups/stern/home/sternd/hormaphis/UTR/hormaphis_cornu_26Sep2017_PoQx8.fasta
second_value:/groups/stern/home/sternd/hormaphis/fq/second/
first_value:/groups/stern/home/sternd/hormaphis/fq/first/
(UTRme) [login2 - sternd@c11u25]~/bin/UTRme/Configuration_Files>ls /groups/stern/home/sternd/hormaphis/UTR/augustus.min.gtf
/groups/stern/home/sternd/hormaphis/UTR/augustus.min.gtf
***********

With all this re-starting, it would be helpful if UTRme could restart from an existing folder. For now, I will subset my data to allow the steps to run quickly.

**Comment by dstern** [comment]
A little progress, but now another problem.

First, a lesson.  I learned that the gtf file must contain "gene" entries, otherwise program does not write the temp.gff file. This is true, even when enter CDS as feature_value

The problem: The sizes.genome file is not writing the sizes of each chromosome. When I run the faidx command in the shell, it correctly produces output with two columns, chromosome name and size
But the sizes.genome file itself contains only the chromosome names, and not the sizes. This appears to cause failure later.

**Comment by sradiouy** [comment]
Hi David. Are you using a tritrypDB genome and annotation file?

Maybe you can send me more information about the run. Can you write to my
personal e-mail? It would be easier to help you.
